# Generated by Django 2.2.1 on 2019-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=120)),
                ('city', models.TextField()),
                ('text', models.TextField()),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
