# Generated by Django 2.2.1 on 2019-06-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='data',
            new_name='data_comments',
        ),
    ]
